[project]
name = "something"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "nltk>=3.9.1",
    "openai>=1.75.0",
    "streamlit>=1.44.1",
]
